include:
  - local: 'templates/template.yml'
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 0.1.${CI_PIPELINE_ID}

stages:
  - build-code
  - build-docker
  - test
  - release
  - deploy

build-code-job:
  stage: build-code
  image: golang:1.17
  variables:
    GOPATH: $CI_PROJECT_DIR/momo-store-app/backend/.go
    CGO_ENABLED: "0"
    GIT_DEPTH: "0"
  before_script:
    - mkdir -p momo-store-app/backend/.go
  script:
    - cd momo-store-app/backend/cmd/api/
    - go build .
    - mkdir -p $CI_PROJECT_DIR/momo-store-app/backend/momo-store-${VERSION}
    - mv api $CI_PROJECT_DIR/momo-store-app/backend/momo-store-${VERSION}/
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - $CI_PROJECT_DIR/momo-store-app/backend/.go/pkg/mod/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/momo-store-app/backend/momo-store-${VERSION}/

build-backend-docker:
  stage: build-docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mv $CI_PROJECT_DIR/momo-store-app/backend/momo-store-${VERSION}/api momo-store-app/backend/
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context $CI_PROJECT_DIR/momo-store-app/backend
      --dockerfile $CI_PROJECT_DIR/momo-store-app/backend/Dockerfile
      --destination ${CI_REGISTRY_IMAGE}/momo-backend:${VERSION}
      --build-arg VERSION=${VERSION}
      --cache=true
      --cache-copy-layers

unit-test:
  stage: test
  image: golang:1.17
  variables:
    GOPATH: $CI_PROJECT_DIR/momo-store-app/backend/.go
    GIT_DEPTH: "0"
  script:
    - cd momo-store-app/backend
    - go test -v ./... 
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - $CI_PROJECT_DIR/momo-store-app/backend/.go/pkg/mod/

sonarqube-backend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd momo-store-app/backend
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_LOGIN} -Dsonar.projectKey=${SONAR_BACKEND_KEY}

gosec-sast:
  variables:
    GOPATH: $CI_PROJECT_DIR/backend/.go
  before_script:
    - |
      cat <<EOF > ~/.netrc
      machine gitlab.praktikum-services.ru
      login $GITLAB_USER_LOGIN
      password $GITLAB_TOKEN
      EOF
  script:
    - /analyzer run --target-dir ${CI_PROJECT_DIR}/backend/
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - $CI_PROJECT_DIR/momo-store-app/backend/.go/pkg/mod/

upload-backend-latest:
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  stage: release
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/momo-backend:$VERSION
    - docker tag $CI_REGISTRY_IMAGE/momo-backend:$VERSION $CI_REGISTRY_IMAGE/momo-backend:latest
    - docker push $CI_REGISTRY_IMAGE/momo-backend:latest

deploy-from-helm:
    extends: 
        - .deploy-from-helm
